REM SETUP PATHS
SET "PATH_WINDEPLOY=C:\IDEs\Qt\5.12.8\mingw73_32\bin\"
SET "PATH_OUTPUT=C:\svn\release\FileSortTool\"
SET "PATH_APPLICATION=C:\svn\build\FileSortTool\release\"
SET "NAME_APPLICATION=FileSortTool.exe"


REM CLEAR OUTPUT DIRECTORY
@RD /S /Q %PATH_OUTPUT%
mkdir %PATH_OUTPUT%

REM GO TO APPLICATION BUID DIRECTORY
cd %PATH_APPLICATION%

REM COPY APPLICATION EXE TO OUTPUT DIRECTORY
xcopy %NAME_APPLICATION% %PATH_OUTPUT%

REM DEPLOY APPLICATION
%cqtdeployer% -bin %NAME_APPLICATION% -qmake %PATH_WINDEPLOY%\qmake.exe -targetDir %PATH_OUTPUT%

PAUSE